### ISSUE TITLE
More of a question...

### ISSUE THREAD

**Issue by JesterDJ** [TheLastProject/ShareToInputStick#46]
Is this for transferring written text onto say a USB stick to then be read by the same app preinstalled on another device without using a Word file for example?

**Comment by TheLastProject** [comment]
It's for [InputStick](http://inputstick.com/), a small little Bluetooth device that acts like a fake keyboard. You use this app (or the official proprietary app) to share text to the device plugged into your computer and it types it like it's a keyboard on your computer.

Do note that due to #6 not using the official proprietary app at least once to set a password is less secure

(Closing this because it's a question, not an issue. That's just for "bookkeeping", nothing personal :))
